name = "GottesmanKnill"
version = "0.1.0"
defaultTargets = ["GottesmanKnill"]

[[lean_lib]]
name = "GottesmanKnill"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"
