import GottesmanKnill.QState
import Mathlib.Algebra.Group.Subgroup.Basic

/-!
# The Clifford group `C_n`

Corresponds to LaTeX section `Clifford.tex`.

`C_n` is defined in `df:Clifford` as the normalizer of `P_n` inside `U_n`,
i.e. those unitaries `c` such that conjugation by `c` sends `P_n` to itself.

Following the paper we want to:

* define `Clifford n` as a subgroup of `Unitary n`,
* produce three families of generators `H_i`, `P_i`, `CNOT_{i,j}`
  (`lem:HinC`, `lem:PinC`, `lem:CNOTinC`),
* state that those generate the whole group (`thm:Clifford`),
* define the "Clifford mapping" `M[c] : PauliOp n → PauliOp n`
  (`df:CliffordMap`).
-/

namespace GottesmanKnill

/-- The image of `PauliOp.toUnitary`: the unitaries that come from a Pauli.
This is the formal version of `P_n ⊆ U_n` used in the definition of the
normalizer. -/
noncomputable def pauliImage (n : ℕ) : Subgroup (Unitary n) :=
  (PauliOp.toUnitary (n := n)).range

/-- The Clifford group `C_n`.

In the paper: `C_n = N(P_n) ∩ U_n`. Since we already have a `Subgroup` of
`Unitary n`, we just take its normalizer.

(`Subgroup.normalizer` in Mathlib is the set of `g` such that `g H g⁻¹ = H`,
matching `df:Normalizer` and `df:Clifford` exactly.) -/
noncomputable def Clifford (n : ℕ) : Subgroup (Unitary n) :=
  Subgroup.normalizer (pauliImage n)

namespace Clifford

variable {n : ℕ}

/-- `cor:pncn`: every Pauli operator is itself a Clifford element.

Hint: any subgroup is contained in its own normalizer (a standard Mathlib
lemma — try `Subgroup.le_normalizer`). -/
theorem pauli_le_clifford : pauliImage n ≤ Clifford n := by
  -- TODO(you): one-liner via Mathlib's `Subgroup.le_normalizer`.
  sorry

/-! ### Generators: `H_i`, `P_i`, `CNOT_{i,j}` are Clifford

The three lemmas `lem:HinC`, `lem:PinC`, `lem:CNOTinC` in the paper depend on
the matrix identities `eq:Basischange`, `eq:phaseconj`, `eq:cnotconj`. In our
abstract setup we *introduce* these gates as opaque unitaries with the
required conjugation behavior. -/

/-- The Hadamard gate on qubit `i`. -/
axiom H {n : ℕ} (i : Fin n) : Unitary n

/-- The phase (`S`) gate on qubit `i`. -/
axiom S {n : ℕ} (i : Fin n) : Unitary n

/-- The CNOT gate with control `i`, target `j`. We require `i ≠ j` —
**TODO(you).** decide whether to bake that into the type. -/
axiom CNOT {n : ℕ} (i j : Fin n) : Unitary n

/-- `lem:HinC`. -/
axiom H_mem_clifford (i : Fin n) : H i ∈ Clifford n

/-- `lem:PinC`. -/
axiom S_mem_clifford (i : Fin n) : S i ∈ Clifford n

/-- `lem:CNOTinC`. -/
axiom CNOT_mem_clifford (i j : Fin n) : CNOT i j ∈ Clifford n

/-- The "generator set" of `C_n`: `{H_i, P_i, CNOT_{i,j}}`. -/
def generators (n : ℕ) : Set (Unitary n) :=
  {u : Unitary n | (∃ i : Fin n, u = H i) ∨ (∃ i : Fin n, u = S i) ∨ (∃ i j : Fin n, u = CNOT i j)}

/-- `thm:Clifford`: the Clifford group is generated by `H`, `S`, `CNOT`.

In Mathlib language: `Clifford n = Subgroup.closure (generators n)`.
This direction `⊆` is the deep one (every Clifford element is a product of
generators); the converse `⊇` follows from the three `_mem_clifford` axioms above. -/
theorem closure_generators : Clifford n = Subgroup.closure (generators n) := by
  sorry  -- TODO(you)

end Clifford

/-! ### The Clifford mapping `M[c]` (`df:CliffordMap`)

For `c ∈ C_n`, conjugation by `c` sends every `P ∈ P_n` to a Pauli, so we get
a map `M[c] : PauliOp n → PauliOp n`. This is the central object of the
"Heisenberg picture" simulation. -/

namespace Clifford

variable {n : ℕ}

/-- `M[c](A) = c A c⁻¹`, viewed as a Pauli (well-defined by membership in the
normalizer).

**TODO(you).** Implementing this requires a *choice*: given `c ∈ C_n` and
`A ∈ P_n`, find the unique `B ∈ P_n` such that `c · toUnitary A · c⁻¹ = toUnitary B`.
That `B` exists by the normalizer condition, and is unique provided
`PauliOp.toUnitary` is injective — which itself needs an axiom or a model.

Hints:
* state and prove `toUnitary_injective : Function.Injective (PauliOp.toUnitary (n := n))`
  as an axiom for now;
* then `mapPauli` can be constructed via `Classical.choose`. -/
noncomputable def mapPauli (c : Clifford n) (A : PauliOp n) : PauliOp n :=
  sorry  -- TODO(you): use `Classical.choose` on the normalizer property.

/-- The defining identity of `M[c]`:
`toUnitary (M[c] A) = c · toUnitary A · c⁻¹`. -/
theorem toUnitary_mapPauli (c : Clifford n) (A : PauliOp n) :
    PauliOp.toUnitary (mapPauli c A) = (c : Unitary n) * PauliOp.toUnitary A * (c : Unitary n)⁻¹ := by
  sorry  -- TODO(you)

/-- The Clifford map `M[c]` is a group hom `P_n → P_n` (`thm:stabCliffordMapHom`). -/
noncomputable def mapPauliHom (c : Clifford n) : PauliOp n →* PauliOp n where
  toFun     := mapPauli c
  map_one'  := by sorry  -- TODO(you): `M[c](1) = 1` from `c · 1 · c⁻¹ = 1`.
  map_mul'  := by sorry  -- TODO(you): `M[c](AB) = M[c](A) M[c](B)`.

end Clifford

end GottesmanKnill
