import GottesmanKnill.StabilizerState
import GottesmanKnill.Clifford

/-!
# Heisenberg picture: evolution of `Stab(ψ)` under unitary conjugation

Corresponds to LaTeX section `Heisenberg.tex`.

The four main results we encode:

* `thm:stabunitary`         : `U · Stab(ψ) · U⁻¹ = Stab(U ψ)`.
* `thm:stabCliffordMapHom`  : the *Clifford mapping* `M[c]` is a group hom.
  (Already half-defined in `Clifford.lean` as `Clifford.mapPauliHom`.)
* `thm:stabCliffordMapIso`  : `M[c]` is an isomorphism, hence `|Stab| = |M[c](Stab)|`.
* `thm:stabgenerate`        : after `m` Clifford gates starting from `|0⟩^⊗n`,
  `Stab(ψ_m)` is still generated by *exactly `n`* Pauli operators.

These are the core results that justify the polynomial-time simulation in the
final Gottesman–Knill theorem.
-/

namespace GottesmanKnill

variable {n : ℕ}

/-- `thm:stabunitary`: stabilizer of `U ψ` is the conjugate of `Stab(ψ)`.

In set-theoretic form: `Stab(U ψ) = U · Stab(ψ) · U⁻¹`.
Spelled out, every `G ∈ Stab(U ψ)` is of the form `U G' U⁻¹` for some
`G' ∈ Stab(ψ)`, and vice versa.

In our setup, `U` ranges over `Unitary n` but the relevant claim is at the level
of `PauliOp n`, valid when `U` is in fact a Clifford element.
-/
theorem stab_unitary (c : Clifford n) (ψ : QState n) (G : PauliOp n) :
    G ∈ Stab ((c : Unitary n) • ψ) ↔
      (Clifford.mapPauliHom c).range.toSubmonoid.carrier.Mem G := by
  sorry  -- TODO(you): adapt the LaTeX argument `G (U ψ) = U ψ ↔ (U⁻¹ G U) ψ = ψ`.

/-- A cleaner form of `thm:stabunitary` in terms of `mapPauliHom`:
`Stab(c ψ)` is the *image* of `Stab(ψ)` under the Clifford map. -/
theorem stab_apply_clifford (c : Clifford n) (ψ : QState n) :
    StabSubgroup ((c : Unitary n) • ψ) = (StabSubgroup ψ).map (Clifford.mapPauliHom c) := by
  sorry  -- TODO(you)

/-! ### Clifford map is a group isomorphism (`thm:stabCliffordMapIso`)

`Clifford.mapPauliHom c` is a `MonoidHom PauliOp PauliOp`. Restricted to
`Stab(ψ)` it lands in `Stab(c ψ)`. We claim that restricted map is bijective. -/

/-- The Clifford map restricted to `Stab(ψ)`. -/
def stabMap (c : Clifford n) (ψ : QState n) :
    StabSubgroup ψ →* StabSubgroup ((c : Unitary n) • ψ) := by
  sorry  -- TODO(you): build the restriction using `Clifford.mapPauliHom c` and
         -- `stab_apply_clifford`.

/-- `thm:stabCliffordMapIso`: the restriction is bijective.

Hint: injectivity comes from `Clifford.mapPauliHom c` having an inverse
(`mapPauliHom c⁻¹`); surjectivity follows from `stab_apply_clifford`. -/
theorem stabMap_bijective (c : Clifford n) (ψ : QState n) :
    Function.Bijective (stabMap c ψ) := by
  sorry  -- TODO(you)

/-- Cardinality corollary: `|Stab(c ψ)| = |Stab(ψ)|`. -/
theorem card_stab_clifford_invariant (c : Clifford n) (ψ : QState n) :
    Nat.card (StabSubgroup ((c : Unitary n) • ψ)) = Nat.card (StabSubgroup ψ) := by
  sorry  -- TODO(you)

/-! ### Generator-preservation (`thm:stabgenerate`)

After applying `m` Clifford unitaries to `|0⟩^⊗n`, the stabilizer is generated by
exactly `n` Pauli operators — namely the images of `Z_1, …, Z_n` under the
composed Clifford map.

Concretely, if `Gs : Fin m → Clifford n` is the gate sequence, set

  ψ_k := (∏_{j<k} (Gs j : Unitary n)) • |0⟩^⊗n.

Then `Stab(ψ_m) = ⟨ M[G_{m-1}] ∘ ⋯ ∘ M[G_0] (Z_1), …, M[G_{m-1}] ∘ ⋯ ∘ M[G_0] (Z_n) ⟩`.
-/

/-- The composed Clifford map after a sequence of `m` gates. -/
noncomputable def composedMap (Gs : List (Clifford n)) : PauliOp n →* PauliOp n :=
  Gs.foldr (fun g acc => acc.comp (Clifford.mapPauliHom g)) (MonoidHom.id _)
  -- TODO(you): check the fold direction; possibly should be `foldl`.

/-- The "tableau" after `m` Clifford gates: the `n` Pauli generators we need to track. -/
noncomputable def tableau (Gs : List (Clifford n)) : Fin n → PauliOp n :=
  fun i => composedMap Gs (PauliOp.singleZ i)

/-- `thm:stabgenerate`: after the gate sequence `Gs` applied to `|0⟩^⊗n`,
the stabilizer is generated by `tableau Gs`. -/
theorem stab_generated_by_tableau (Gs : List (Clifford n)) :
    let ψ := (Gs.map (fun g => (g : Unitary n))).foldr (· * ·) 1 • QState.zero n
    StabSubgroup ψ = Subgroup.closure (Set.range (tableau Gs)) := by
  sorry  -- TODO(you): induction on `Gs`, using `stab_zero_eq` and
         -- `stab_apply_clifford` at each step.

end GottesmanKnill
