import GottesmanKnill.Stabilizer
import GottesmanKnill.Clifford

/-!
# Stabilizer states

Corresponds to LaTeX section `stabilizerstate.tex`.

A *stabilizer state* is one that is uniquely determined (up to global phase) by
its stabilizer subgroup. The key theorems we encode:

* `thm:stabilizerof0` : `Stab(|0⟩^⊗n) = ⟨Z_1, …, Z_n⟩` and has size `2^n`.
* `thm:numberPauli`   : every stabilizer state has exactly `2^n` stabilizers.
* `thm:oneonemap`     : the map `ψ ↦ Stab(ψ)` is *injective* on stabilizer states,
                        which the LaTeX informally describes as a "bijection".
-/

namespace GottesmanKnill

variable {n : ℕ}

/-- The subgroup generated by `Z_1, …, Z_n` inside `P_n`. -/
def standardZGroup (n : ℕ) : Subgroup (PauliOp n) :=
  Subgroup.closure (Set.range (PauliOp.singleZ (n := n)))

/-- `thm:stabilizerof0` (first half): every `Z_i` stabilizes `|0⟩^⊗n`.

Hint: `QState.zero_stabilized_by_Z`. -/
theorem singleZ_mem_stab_zero (i : Fin n) :
    PauliOp.singleZ i ∈ Stab (QState.zero n) := by
  sorry  -- TODO(you)

/-- `thm:stabilizerof0` (full statement): the stabilizer of `|0⟩^⊗n` is exactly
the subgroup generated by `Z_1, …, Z_n`, and it has size `2^n`. -/
theorem stab_zero_eq : StabSubgroup (QState.zero n) = standardZGroup n := by
  -- LaTeX-level hints:
  -- ⊇  every Z_i ∈ Stab(|0⟩^⊗n) by `singleZ_mem_stab_zero`, plus closure.
  -- ⊆  any A ∈ Stab(|0⟩^⊗n) must have only I's and Z's by `eq:Astab0`.
  sorry  -- TODO(you)

/-- Cardinality version. -/
theorem card_stab_zero :
    Nat.card (StabSubgroup (QState.zero n)) = 2 ^ n := by
  -- Hint: combine `stab_zero_eq` with the fact that `⟨Z_1,…,Z_n⟩ ≃ (Fin n → Bool)`.
  sorry  -- TODO(you)

/-! ### Stabilizer states proper -/

/-- A state `ψ` is a **stabilizer state** if it can be obtained from `|0⟩^⊗n`
by a Clifford unitary.

This matches the LaTeX's working definition (in `thm:oneonemap` and the
Heisenberg section): we only consider states reachable from `|0⟩^⊗n` by
Clifford gates. -/
def IsStabilizerState (ψ : QState n) : Prop :=
  ∃ c : Clifford n, ψ = (c : Unitary n) • QState.zero n

/-- `thm:numberPauli`: every stabilizer state has exactly `2^n` stabilizers. -/
theorem card_stab_of_stabState {ψ : QState n} (hψ : IsStabilizerState ψ) :
    Nat.card (StabSubgroup ψ) = 2 ^ n := by
  -- Hint: `Stab(c · |0⟩) = c · Stab(|0⟩) · c⁻¹` (proved later in `Heisenberg.lean`),
  -- and conjugation is bijective so it preserves cardinality.
  sorry  -- TODO(you)

/-- `thm:oneonemap`: the map `ψ ↦ Stab(ψ)` is injective on stabilizer states.

The LaTeX argues by contradiction using orthogonality of the `±1`-eigenspaces
of a stabilizer (`thm:OrthSubspace`). In our abstract setup we can state this
as: if two stabilizer states have the same stabilizer subgroup, they are
*equal up to global phase*.

**TODO(you).** Decide how to handle the "up to global phase" subtlety:
* (a) introduce a setoid on `QState n` quotienting out by phases, or
* (b) bake an orthogonality axiom into `QState` that lets you derive `ψ = φ`
      under additional structure.
The paper's `thm:OrthSubspace` corresponds to (b). -/
theorem stab_injective {ψ φ : QState n}
    (hψ : IsStabilizerState ψ) (hφ : IsStabilizerState φ)
    (h : StabSubgroup ψ = StabSubgroup φ) : ψ = φ := by
  sorry  -- TODO(you): see the LaTeX proof via |ψ'⟩, |φ'⟩ and `thm:OrthSubspace`.

end GottesmanKnill
